var APPS={'cine':{title:'CINE // HUB',path:'script/Apps/Cine/index.html',icon:'https://cdn.worldvectorlogo.com/logos/netflix-logo-icon.svg',pinned:true},'term':{title:'Spotify',path:'script/Apps/Spotify/index.html',icon:'https://cdn.pixabay.com/photo/2016/10/22/00/15/spotify-1759471_1280.jpg',pinned:true},'files':{title:'PS5 Emu',path:'script/Apps/Ps5/index.html',icon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-OeL_be7RFaoHi3PswkuAR5XcMgBNRDynsg&s',pinned:true},'web':{title:'Cine-Web',path:'script/Apps/Web/index.html',icon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeD89ZcX5W1FBtal7RerasT27q-OmZqnBixQ&s',pinned:true},'settings':{title:'CONFIG',internal:true,icon:'https://cdn.iconscout.com/icon/free/png-256/free-apple-settings-icon-svg-download-png-493162.png',pinned:true},'discord':{title:'Discord',path:'https://discord.com/app',icon:'https://assets-global.website-files.com/6257adef93867e50d84d30e2/636e0a6a49cf127bf92de1e2_icon_clyde_blurple_RGB.png',pinned:false}};
let wallpaperRegistry={"Default":{id:"Default",name:"Snake Skeleton",url:"Videos/default.mp4",locked:false},"green":{id:"green",name:"Green Anime",url:"Videos/green.mp4",locked:false},"#v2-Release":{id:"v2-Release",name:"Hunt",url:"Videos/Hunt.mp4",locked:true},"#Minecraft01":{id:"Tree",name:"Tree Of Life",url:"Videos/Minecraft01.mp4",locked:true},"#45E33":{id:"SnowFall",name:"Snow Fall",url:"Videos/45E33.mp4",locked:true},"#Minecraft02":{id:"Minecraft02",name:"Sakura Pond",url:"Videos/Minecraft02.mp4",locked:true},"#Minecraft03":{id:"Minecraft03",name:"Minecraft Paradise",url:"Videos/Minecraft03.mp4",locked:true}};
var sysConfig=JSON.parse(localStorage.getItem('cine_sys_config'))||{optBg:false,shortBoot:false,panicKey:'`',homeWallpaper:'Default',lockWallpaper:'green',cloak:'none',wpLoop:false,idleLock:false,redirPrompt:false};
if(sysConfig.wpLoop===undefined)sysConfig.wpLoop=false;if(sysConfig.idleLock===undefined)sysConfig.idleLock=false;if(sysConfig.redirPrompt===undefined)sysConfig.redirPrompt=false;
if(!sysConfig.panicKey)sysConfig.panicKey='`';if(!sysConfig.homeWallpaper)sysConfig.homeWallpaper='Default';if(!sysConfig.lockWallpaper)sysConfig.lockWallpaper='green';
window.updateSysSetting=function(k,v){sysConfig[k]=v;localStorage.setItem('cine_sys_config',JSON.stringify(sysConfig));if(k==='optBg'||k==='wpLoop')updateWallpaperLoop();if(k==='redirPrompt')setupRedirectionPrompts();};
const cloaks={none:{title:"Cine-OS",icon:""},google:{title:"Google",icon:"https://www.google.com/favicon.ico"},drive:{title:"My Drive - Google Drive",icon:"https://ssl.gstatic.com/images/branding/product/1x/drive_2020q4_32dp.png"},canvas:{title:"Dashboard",icon:"https://du11hjcvx0uqb.cloudfront.net/br/dist/images/favicon-e10d657a73.ico"},classroom:{title:"Classes",icon:"https://ssl.gstatic.com/classroom/favicon.png"}};
window.updateCloak=function(k){sysConfig.cloak=k;localStorage.setItem('cine_sys_config',JSON.stringify(sysConfig));applyCloak();};
function applyCloak(){let k=sysConfig.cloak||'none';let c=cloaks[k];let e=document.querySelectorAll("link[rel*='icon']");e.forEach(l=>l.remove());if(c&&k!=='none'){document.title=c.title;let l=document.createElement('link');l.type='image/x-icon';l.rel='shortcut icon';l.href=c.icon;document.getElementsByTagName('head')[0].appendChild(l);}else{document.title="Restricted Access Network";}}setInterval(applyCloak,2000);

let isDesktopActive=false;let bootActive=true;let enterCount=0;let highestZ=500;let activeWindowId=null;let isMediaPlaying=false;
let keyHistory=[];const secretCombo=['ArrowUp','ArrowDown','ArrowUp','ArrowDown'];

// CIRI POPUP VARS
let ciriHoldTimer=null;let isCiriActive=false;let hasBootedCiri=false;
const uiBody=document.body;

document.addEventListener('keydown',function(event){
 const fb=document.getElementById('fake-block-screen');
 if(fb&&!fb.classList.contains('hidden-block')){
  keyHistory.push(event.key);if(keyHistory.length>secretCombo.length)keyHistory.shift();
  if(JSON.stringify(keyHistory)===JSON.stringify(secretCombo)){fb.classList.add('hidden-block');document.getElementById('boot-layer').style.display='flex';document.title="Cine-OS V2";applyCloak();}
 }else{
  if(bootActive&&event.key==='Enter'&&document.getElementById('boot-layer').style.display!=='none'){enterCount++;if(enterCount>=2)skipBootSequence();setTimeout(()=>{enterCount=0;},500);}
  if(event.key&&sysConfig.panicKey&&event.key.toLowerCase()===sysConfig.panicKey.toLowerCase()){window.location.href="https://google.com";}
  if(event.altKey&&(event.code==='KeyS'||event.key.toLowerCase()==='s')){
   if(!ciriHoldTimer&&!isCiriActive){
    ciriHoldTimer=setTimeout(()=>{uiBody.classList.add('ciri-active');isCiriActive=true;
     if(!hasBootedCiri){
      const bootS=document.getElementById('ciri-boot-screen');const bootC=document.getElementById('boot-ciri-text');const bootSb=document.getElementById('boot-sub-text');const bootL=document.getElementById('boot-loader');const bootST=document.getElementById('boot-status-text');const bootSp=document.getElementById('boot-spinner');
      bootS.style.display='flex';setTimeout(()=>bootC.classList.add('typing'),300);setTimeout(()=>bootSb.classList.add('show'),1100);
      setTimeout(()=>{bootL.style.opacity='1';const pingS=Date.now();fetch('https://generativelanguage.googleapis.com/v1beta/models').then(()=>hnr("Connection Established.")).catch(()=>hnr("Network Restricted."));
       function hnr(msg){const el=Date.now()-pingS;const rem=Math.max(0,1500-el);setTimeout(()=>{bootST.textContent=msg;bootSp.style.display='none';setTimeout(()=>{bootS.style.filter='blur(10px)';bootS.style.opacity='0';setTimeout(()=>{bootS.style.display='none';hasBootedCiri=true;document.getElementById('chat-input').focus();},800);},1800);},rem);}
      },2200);
     }else{setTimeout(()=>document.getElementById('chat-input').focus(),100);}
    },1000);
   }
  }else if(event.code==='Escape'&&isCiriActive)window.closeCiri();
 }
});
document.addEventListener('keyup',(e)=>{if(e.code==='KeyS'||e.key.toLowerCase()==='s'||e.key==='Alt'){clearTimeout(ciriHoldTimer);ciriHoldTimer=null;}});

const isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
if(isMobile){document.getElementById('mobile-warning').classList.add('show-warning');let lt=0;document.getElementById('mobile-warning').addEventListener('touchstart',(e)=>{let ct=new Date().getTime();let tl=ct-lt;if(tl<500&&tl>0){document.getElementById('mobile-warning').classList.remove('show-warning');}lt=ct;});document.getElementById('mobile-warning').addEventListener('dblclick',()=>{document.getElementById('mobile-warning').classList.remove('show-warning');});}

async function loadDynamicResources(){
 try{let r=await fetch('Videos/');if(r.ok){let t=await r.text();let m=t.match(/href="([^"]+\.mp4)"/g);if(m){m.forEach(x=>{let f=x.replace('href="','').replace('"','');if(f.startsWith('#')&&!wallpaperRegistry[f]){let n=f.replace('#','').replace('.mp4','');wallpaperRegistry[f]={id:n,name:n,url:"Videos/"+f,locked:true};}});}}}catch(e){}
 try{let r=await fetch('script/Apps/');if(r.ok){let t=await r.text();let dirs=t.match(/href="([^"]+\/)"/g);if(dirs){dirs.forEach(d=>{let fn=d.replace('href="','').replace(/"/g,'').replace('/','');if(fn&&!APPS[fn.toLowerCase()]&&fn!=='Cine'&&fn!=='Spotify'){APPS[fn.toLowerCase()]={title:fn,path:`script/Apps/${fn}/index.html`,icon:'https://cdn-icons-png.flaticon.com/512/732/732244.png',pinned:false};}});}}}catch(e){}
 renderUI();initWallpapers();
}

document.addEventListener("DOMContentLoaded",()=>{loadDynamicResources();loadDesktop();setupRedirectionPrompts();checkApiKeyStatus();});
function renderUI(){var dc=document.getElementById('dock-container');dc.innerHTML=`<div class="dock-item" onclick="toggleStartMenu()"><img src="https://missionsupport.archden.org/wp-content/uploads/2022/02/windows11-icon.png"></div><div class="dock-sep"></div><div class="dock-item" onclick="toggleAppDrawer()"><svg width="24" height="24" viewBox="0 0 24 24" fill="#aaa"><path d="M4 4h4v4H4zm6 0h4v4h-4zm6 0h4v4h-4zM4 10h4v4H4zm6 0h4v4h-4zm6 0h4v4h-4zM4 16h4v4H4zm6 0h4v4h-4zm6 0h4v4h-4z"/></svg></div><div class="dock-sep"></div>`;
for(let id in APPS){if(APPS[id].pinned)dc.innerHTML+=`<div class="dock-item" data-id="${id}" onmousedown="DragSystem.start(event,this,'dock','${id}')" onclick="toggleApp('${id}')"><img src="${APPS[id].icon}"></div>`;}
var pg=document.getElementById('pinned-grid');pg.innerHTML='';for(let id in APPS){if(APPS[id].pinned)pg.innerHTML+=`<div class="pinned-item" onclick="toggleApp('${id}')"><img src="${APPS[id].icon}"><span>${APPS[id].title}</span></div>`;}populateDrawer();}

window.startBootSequence=function(){var c=document.getElementById('boot-content');var b=document.getElementById('boot-video');c.style.display='none';b.style.display='block';b.muted=false;b.volume=1.0;if(sysConfig.shortBoot){b.src="Videos/QuickBoot.mp4";b.load();}b.play().catch(()=>{b.muted=true;b.play();});b.onended=()=>{if(bootActive)skipBootSequence();};};
window.skipBootSequence=function(){if(!bootActive)return;bootActive=false;var l=document.getElementById('boot-layer');var b=document.getElementById('boot-video');if(b)b.pause();if(l){l.style.opacity='0';document.getElementById('lock-screen').classList.add('active');var lV=document.getElementById('lock-video');lV.play().catch(e=>{});setTimeout(()=>{l.style.display='none';},600);updateClock();}};

function showNotification(t, m){const c=document.getElementById('toast-container');const ts=document.createElement('div');ts.className='toast-notification';ts.innerHTML=`<div class="toast-header"><div class="toast-app-info"><div class="toast-icon"><i class="fas fa-bell"></i></div><span>System</span></div><i class="fas fa-times toast-close"></i></div><div class="toast-title">${t}</div><div class="toast-body">${m}</div>`;c.appendChild(ts);setTimeout(()=>ts.classList.add('show'),100);const ct=()=>{ts.classList.remove('show');setTimeout(()=>ts.remove(),400);};ts.onclick=ct;setTimeout(ct,6000);}
let welcomeShown=false;window.unlockSystem=function(){var s=document.getElementById('lock-screen');s.classList.add('slide-up');setTimeout(()=>{s.classList.remove('active');isDesktopActive=true;document.getElementById('lock-video').pause();if(!sysConfig.optBg)document.getElementById('bg-video').play().catch(e=>{});if(!welcomeShown){showNotification("Welcome To Cine V2","Checkout Settings for FAQ!");welcomeShown=true;}},600);resetIdle();};

function initWallpapers(){var bgV=document.getElementById('bg-video');var lV=document.getElementById('lock-video');if(wallpaperRegistry[sysConfig.homeWallpaper]){bgV.src=wallpaperRegistry[sysConfig.homeWallpaper].url;bgV.load();}if(wallpaperRegistry[sysConfig.lockWallpaper]){lV.src=wallpaperRegistry[sysConfig.lockWallpaper].url;lV.load();}else{lV.src="Videos/green.mp4";lV.load();}updateWallpaperLoop();let chk=document.getElementById('wp-loop-chk');if(chk)chk.checked=sysConfig.wpLoop;}
function updateWallpaperLoop(){var bgV=document.getElementById('bg-video');var lV=document.getElementById('lock-video');if(bgV)bgV.loop=sysConfig.wpLoop;if(lV)lV.loop=sysConfig.wpLoop;if(sysConfig.optBg){if(bgV)bgV.pause();}else if(isDesktopActive&&bgV&&bgV.paused){bgV.play().catch(e=>{});}}
function updateClock(){var n=new Date();var d=['SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY'];var hrs=n.getHours();var gr='GOOD EVENING';if(hrs<12)gr='GOOD MORNING';else if(hrs<18)gr='GOOD AFTERNOON';var lG=document.getElementById('lock-greet');if(lG)lG.innerText=gr;var h12=hrs%12||12;var ampm=hrs>=12?'PM':'AM';var min=n.getMinutes().toString().padStart(2,'0');var lT=document.getElementById('lock-time');if(lT)lT.innerText=`${h12}:${min} ${ampm}`;var fM=['JANUARY','FEBRUARY','MARCH','APRIL','MAY','JUNE','JULY','AUGUST','SEPTEMBER','OCTOBER','NOVEMBER','DECEMBER'];var lD=document.getElementById('lock-date');if(lD)lD.innerText=`${n.getDate().toString().padStart(2,'0')} ${fM[n.getMonth()]}`;var dL=document.getElementById('lock-day-large');if(dL)dL.innerText=d[n.getDay()];var hd=document.getElementById('lbl-day');if(hd)hd.innerText=d[n.getDay()];}setInterval(updateClock,1000);

let idleTime=0;function resetIdle(){idleTime=0;}document.addEventListener('mousemove',resetIdle);document.addEventListener('keypress',resetIdle);document.addEventListener('click',resetIdle);
setInterval(()=>{idleTime++;var s=document.getElementById('lock-screen');if(sysConfig.idleLock&&idleTime>=180&&!s.classList.contains('active')&&!bootActive&&document.getElementById('fake-block-screen').classList.contains('hidden-block')){if(isMediaPlaying){idleTime=0;}else{isDesktopActive=false;s.classList.remove('slide-up');s.classList.add('active');document.getElementById('bg-video').pause();document.getElementById('lock-video').play().catch(e=>{});}}},1000);

function populateDrawer(){var dg=document.getElementById('drawer-grid');dg.innerHTML='';for(var key in APPS){var a=APPS[key];var d=document.createElement('div');d.className='drawer-item';d.dataset.id=key;d.onmousedown=(e)=>{DragSystem.start(e,d,'drawer',key);};d.onclick=()=>{toggleApp(key);toggleAppDrawer();};d.innerHTML=`<img src="${a.icon}" style="pointer-events:none;"><span>${a.title}</span>`;dg.appendChild(d);}}
window.filterDrawer=function(v){var items=document.querySelectorAll('.drawer-item');v=v.toLowerCase();items.forEach(i=>{if(i.innerText.toLowerCase().includes(v))i.style.display='flex';else i.style.display='none';});};
window.toggleAppDrawer=function(){var d=document.getElementById('app-drawer');if(d.classList.contains('open')){d.classList.remove('open');setTimeout(()=>d.style.display='none',300);}else{d.style.display='block';setTimeout(()=>d.classList.add('open'),10);}};

window.toggleApp=function(id){var w=document.getElementById(`win-${id}`);if(w){if(w.classList.contains('minimized')){w.classList.remove('minimized');w.classList.add('active');w.style.zIndex=++highestZ;activeWindowId=id;startImmersiveMode(w);}else if(activeWindowId===id){minimizeWindow(id);}else{w.style.zIndex=++highestZ;activeWindowId=id;startImmersiveMode(w);}}else{openWindow(id);}};
function openWindow(id){var sm=document.getElementById('start-menu');if(sm){sm.classList.remove('open');setTimeout(()=>{sm.style.display='none';},300);}var l=document.getElementById('windows-layer');var w=document.getElementById(`win-${id}`);if(!w){var d=APPS[id]||{title:'APP',path:'about:blank'};w=document.createElement('div');w.id=`win-${id}`;w.className='window active header-visible';w.style.zIndex=++highestZ;var ih=d.internal?`<iframe id="frame-${id}"></iframe>`:`<iframe id="frame-${id}" src="${d.path}"></iframe>`;w.innerHTML=`<div class="win-header" onmousedown="DragSystem.startWinDrag(event, '${id}')"><div class="win-title">${d.title}</div><div class="win-controls"><div class="win-btn btn-min" onclick="minimizeWindow('${id}')"></div><div class="win-btn btn-close" onclick="closeWindow('${id}')"></div></div></div><div class="win-body">${ih}</div>`;l.appendChild(w);if(d.internal){var t=document.getElementById('code-settings');var f=document.getElementById(`frame-${id}`);if(t&&f){f.onload=()=>{var dc=f.contentWindow.document;dc.open();dc.write(`<html><head><link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@900&family=Rajdhani:wght@400;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"><style>body{background:transparent;color:#fff;font-family:'Rajdhani',sans-serif;padding:25px;}</style></head><body>${t.innerHTML}</body></html>`);dc.close();if(f.contentWindow.document.getElementById('chk-bg')){f.contentWindow.document.getElementById('chk-bg').checked=sysConfig.optBg;f.contentWindow.document.getElementById('chk-boot').checked=sysConfig.shortBoot;f.contentWindow.document.getElementById('chk-idle').checked=sysConfig.idleLock;f.contentWindow.document.getElementById('chk-redir').checked=sysConfig.redirPrompt;f.contentWindow.document.getElementById('panic-input').value=sysConfig.panicKey;f.contentWindow.document.getElementById('cloak-select').value=sysConfig.cloak;}};}}}else{w.classList.remove('minimized');w.classList.add('active');w.style.zIndex=++highestZ;}activeWindowId=id;startImmersiveMode(w);}

window.closeWindow=function(id){var w=document.getElementById(`win-${id}`);if(w)w.remove();if(activeWindowId===id)activeWindowId=null;endImmersiveMode();};
window.minimizeWindow=function(id){var w=document.getElementById(`win-${id}`);if(w){w.classList.add('minimized');w.classList.remove('active');if(activeWindowId===id)activeWindowId=null;}endImmersiveMode();};
function startImmersiveMode(w){document.getElementById('dock-container').classList.add('dock-hidden');w.classList.remove('header-visible');}
function endImmersiveMode(){const aw=document.querySelectorAll('.window.active:not(.minimized)');if(aw.length===0){document.getElementById('dock-container').classList.remove('dock-hidden');activeWindowId=null;}else{let lw=aw[aw.length-1];activeWindowId=lw.id.replace('win-','');lw.style.zIndex=++highestZ;startImmersiveMode(lw);}}

let dockTimer;const dockEl=document.getElementById('dock-container');
document.getElementById('bottom-trigger').addEventListener('mouseenter',()=>{dockEl.classList.remove('dock-hidden');clearTimeout(dockTimer);});
dockEl.addEventListener('mouseleave',()=>{const aw=document.querySelectorAll('.window.active:not(.minimized)');if(aw.length>0){dockTimer=setTimeout(()=>dockEl.classList.add('dock-hidden'),1000);}});
dockEl.addEventListener('mouseenter',()=>clearTimeout(dockTimer));
document.getElementById('top-trigger').addEventListener('mouseenter',()=>{if(activeWindowId){var w=document.getElementById(`win-${activeWindowId}`);if(w&&!w.classList.contains('minimized'))w.classList.add('header-visible');}});
document.addEventListener('mouseover',e=>{if(e.target.closest('.win-header')){if(activeWindowId){let ww=document.getElementById(`win-${activeWindowId}`);if(ww)ww.classList.add('header-visible');}}else if(activeWindowId&&!e.target.closest('#top-trigger')){var w=document.getElementById(`win-${activeWindowId}`);if(w)w.classList.remove('header-visible');}});

let desktopLayout=JSON.parse(localStorage.getItem('cine_desktop_v2'))||[];
function loadDesktop(){document.querySelectorAll('.desktop-app').forEach(e=>e.remove());desktopLayout.forEach((i,idx)=>{let d=document.createElement('div');d.className='desktop-app';d.style.left=i.x+'px';d.style.top=i.y+'px';d.dataset.idx=idx;if(i.type==='folder'){let g=`<div class="d-folder-grid">`;i.apps.slice(0,4).forEach(a=>{if(APPS[a])g+=`<img src="${APPS[a].icon}">`;});g+=`</div><div class="d-label">Folder</div>`;d.innerHTML=g;d.onclick=()=>{openFolderView(idx);};}else{let a=APPS[i.id];if(a){d.innerHTML=`<img src="${a.icon}" class="d-icon"><div class="d-label">${a.title}</div>`;d.onclick=()=>{toggleApp(i.id);};}}
d.onmousedown=(ev)=>{ev.stopPropagation();let moved=false;let sx=ev.clientX,sy=ev.clientY;const mm=(em)=>{if(Math.abs(em.clientX-sx)>3||Math.abs(em.clientY-sy)>3){moved=true;DragSystem.start(em,d,'desktop',idx);d.removeEventListener('mousemove',mm);}};d.addEventListener('mousemove',mm);d.addEventListener('mouseup',()=>{d.removeEventListener('mousemove',mm);},{once:true});};document.getElementById('desktop-area').appendChild(d);});}
function saveDesktop(){localStorage.setItem('cine_desktop_v2',JSON.stringify(desktopLayout));loadDesktop();}

window.openFolderView=function(idx){const fOverlay=document.getElementById('folder-view-overlay');const fBox=document.getElementById('folder-view-box');fBox.innerHTML='';let fData=desktopLayout[idx];if(fData&&fData.type==='folder'){fData.apps.forEach(aId=>{let app=APPS[aId];if(app){let ai=document.createElement('div');ai.className='folder-item';ai.innerHTML=`<img src="${app.icon}"><span>${app.title}</span>`;ai.onclick=(e)=>{e.stopPropagation();toggleApp(aId);closeFolderView();};fBox.appendChild(ai);}});fOverlay.style.display='flex';setTimeout(()=>fOverlay.classList.add('open'),10);}};
window.closeFolderView=function(e){const fOverlay=document.getElementById('folder-view-overlay');if(e&&e.target&&e.target.closest('#folder-view-box'))return;fOverlay.classList.remove('open');setTimeout(()=>fOverlay.style.display='none',300);};

window.DragSystem={dragging:false,startPos:{x:0,y:0},sourceType:null,sourceEl:null,idx:null,appId:null,proxy:document.getElementById('drag-proxy'),pImg:document.getElementById('proxy-img'),badge:document.getElementById('folder-badge'),
init(){window.addEventListener('mousemove',e=>this.move(e));window.addEventListener('mouseup',e=>this.end(e));},
start(e,el,type,idx_or_id){this.startPos={x:e.clientX,y:e.clientY};this.sourceType=type;this.sourceEl=el;this.isDragMove=false;if(type==='drawer'){this.appId=idx_or_id;}else if(type==='dock'){this.appId=idx_or_id;}else if(type==='desktop'){this.idx=idx_or_id;this.sourceEl.style.opacity='0.5';}},
startWinDrag(e,id){this.startPos={x:e.clientX,y:e.clientY};this.sourceType='window';this.sourceEl=document.getElementById(`win-${id}`);this.isDragMove=false;},
move(e){if(!this.sourceEl)return;var dx=Math.abs(e.clientX-this.startPos.x),dy=Math.abs(e.clientY-this.startPos.y);if(dx>3||dy>3){this.dragging=true;this.isDragMove=true;if(this.sourceType==='desktop'||this.sourceType==='drawer'||this.sourceType==='dock'){if(this.sourceType==='drawer')toggleAppDrawer();this.proxy.style.display='block';this.proxy.style.left=(e.clientX-25)+'px';this.proxy.style.top=(e.clientY-25)+'px';if(this.sourceType==='drawer'||this.sourceType==='dock'){if(APPS[this.appId])this.pImg.src=APPS[this.appId].icon;}else if(desktopLayout[this.idx].type==='app'){if(APPS[desktopLayout[this.idx].id])this.pImg.src=APPS[desktopLayout[this.idx].id].icon;}else{this.pImg.src='';this.badge.style.display='flex';this.badge.innerText=desktopLayout[this.idx].apps.length;}}}},
end(e){if(!this.sourceEl)return;if(!this.dragging){this.reset();return;}
if(this.sourceType==='desktop'||this.sourceType==='drawer'||this.sourceType==='dock'){let nx=Math.round((e.clientX-40)/90)*90;let ny=Math.round((e.clientY-40)/100)*100;
if(e.clientY>window.innerHeight-80){if(this.sourceType==='desktop')desktopLayout.splice(this.idx,1);}else{let targetIdx=-1;document.querySelectorAll('.desktop-app').forEach(app=>{if(app!==this.sourceEl){let r=app.getBoundingClientRect();if(e.clientX>r.left&&e.clientX<r.right&&e.clientY>r.top&&e.clientY<r.bottom)targetIdx=app.dataset.idx;}});
if(targetIdx>-1){let t=desktopLayout[targetIdx];let droppedApps=(this.sourceType==='drawer'||this.sourceType==='dock')?[this.appId]:(desktopLayout[this.idx].type==='app'?[desktopLayout[this.idx].id]:desktopLayout[this.idx].apps);
if(t.type==='app'){t.type='folder';t.apps=[t.id,...droppedApps];delete t.id;}else{t.apps.push(...droppedApps);}if(this.sourceType==='desktop')desktopLayout.splice(this.idx,1);}else{if(this.sourceType==='drawer'||this.sourceType==='dock')desktopLayout.push({type:'app',id:this.appId,x:nx,y:ny});else{desktopLayout[this.idx].x=nx;desktopLayout[this.idx].y=ny;}}}saveDesktop();}this.reset();},
reset(){this.dragging=false;if(this.sourceEl)this.sourceEl.style.opacity='1';this.sourceEl=null;this.proxy.style.display='none';this.badge.style.display='none';}};DragSystem.init();

window.toggleDesktopSize=function(isLarge){if(isLarge)document.getElementById('desktop-area').classList.add('desktop-large-mode');else document.getElementById('desktop-area').classList.remove('desktop-large-mode');document.getElementById('desktop-context-menu').style.display='none';};
let unlockedWallpapers=JSON.parse(localStorage.getItem('cine_unlocked_wp'))||['default'];window.wpMode='both';
document.addEventListener('contextmenu',e=>{var v=['desktop-area','windows-layer','bg-video','snow-fx'];if(v.includes(e.target.id)||e.target.tagName==='BODY'){e.preventDefault();var c=document.getElementById('desktop-context-menu');c.style.display='block';var x=e.pageX,y=e.pageY;if(x+200>window.innerWidth)x=window.innerWidth-200;if(y+100>window.innerHeight)y=window.innerHeight-100;c.style.left=x+'px';c.style.top=y+'px';}});
document.addEventListener('click',e=>{var c=document.getElementById('desktop-context-menu');if(c&&!c.contains(e.target))c.style.display='none';});
window.setWallpaper=function(k,i=false){var d=wallpaperRegistry[k];if(!d)return;if(i&&d.locked&&!unlockedWallpapers.includes(d.id)){unlockedWallpapers.push(d.id);localStorage.setItem('cine_unlocked_wp',JSON.stringify(unlockedWallpapers));alert(`Wallpaper: [ ${d.name} ] Unlocked.`);}if(window.wpMode==='home'||window.wpMode==='both'){var v=document.getElementById('bg-video');v.src=d.url;v.load();if(!document.getElementById('lock-screen').classList.contains('active'))v.play();updateSysSetting('homeWallpaper',k);}if(window.wpMode==='lock'||window.wpMode==='both'){var l=document.getElementById('lock-video');l.src=d.url;l.load();if(document.getElementById('lock-screen').classList.contains('active'))l.play();updateSysSetting('lockWallpaper',k);}updateWallpaperLoop();openWallpaperMenu();};
window.openWallpaperMenu=function(){var m=document.getElementById('wallpaper-menu');var gu=document.getElementById('wp-grid-unlocked');var gl=document.getElementById('wp-grid-locked');gu.innerHTML='';gl.innerHTML='';for(const[k,d] of Object.entries(wallpaperRegistry)){var u=!d.locked||unlockedWallpapers.includes(d.id);var c=document.createElement('div');c.className=`wp-card ${u?'':'wp-locked'}`;if(u){c.innerHTML=`<video src="${d.url}" preload="auto" playsinline muted loop onmouseover="this.play()" onmouseout="this.pause()"></video><div class="wp-info">${d.name}</div>`;c.onclick=()=>{setWallpaper(k);document.querySelectorAll('.wp-card').forEach(e=>e.classList.remove('active-wp'));c.classList.add('active-wp');};gu.appendChild(c);}else{c.innerHTML=`<div class="wp-info"><i class="fas fa-lock"></i></div>`;gl.appendChild(c);}}m.classList.add('open');let chk=document.getElementById('wp-loop-chk');if(chk){chk.checked=sysConfig.wpLoop;chk.onchange=(e)=>updateSysSetting('wpLoop',e.target.checked);}};
var si=document.getElementById('start-search-input');if(si){si.addEventListener('keydown',function(e){if(e.key==='Enter'){var q=this.value.trim();if(wallpaperRegistry[q]){setWallpaper(q,true);this.value="";this.blur();}}});}
window.toggleStartMenu=function(){var s=document.getElementById('start-menu');if(s.classList.contains('open')){s.classList.remove('open');setTimeout(()=>s.style.display='none',300);}else{s.style.display='flex';setTimeout(()=>s.classList.add('open'),10);}};
document.addEventListener('click',e=>{var s=document.getElementById('start-menu');if(s&&!s.contains(e.target)&&!e.target.closest('.dock-item')){s.classList.remove('open');setTimeout(()=>s.style.display='none',300);}});

var ctxSnow=document.getElementById('snow-fx').getContext('2d');var ww=window.innerWidth,wh=window.innerHeight;document.getElementById('snow-fx').width=ww;document.getElementById('snow-fx').height=wh;var flakes=Array.from({length:30},()=>({x:Math.random()*ww,y:Math.random()*wh,r:Math.random()*2,s:Math.random()+0.5}));function drawSnow(){if(isDesktopActive){ctxSnow.clearRect(0,0,ww,wh);ctxSnow.fillStyle="rgba(255,255,255,0.3)";flakes.forEach(f=>{ctxSnow.beginPath();ctxSnow.arc(f.x,f.y,f.r,0,Math.PI*2);ctxSnow.fill();f.y+=f.s;if(f.y>wh)f.y=0;});}requestAnimationFrame(drawSnow);}drawSnow();

// REDIRECTION PROMPTS
function setupRedirectionPrompts(){
 if(sysConfig.redirPrompt){
  window.onbeforeunload=function(){return "Leaving CINE-OS. Are you sure?";};
  document.addEventListener('click',(e)=>{let a=e.target.closest('a');if(a&&a.href&&!a.href.startsWith('javascript:')){e.preventDefault();if(confirm(`Leaving CINE-OS to: \n\n${a.href}\n\nDo you want to proceed?`)){window.location.href=a.href;}}});
 }else{
  window.onbeforeunload=null;
 }
}

// CIRI POPUP LOGIC 
const MODES=['FAST','THINKING','LIVE'];let currentModeIndex=0;let expectingApiKey=false;let screenStream=null;let currentImageBase64=null;let currentImageMime=null;
const svgSecure=`<svg class="secure-svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" style="width:14px;height:14px;stroke:#fff"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path><path d="M9 12l2 2 4-4"></path></svg>`;const svgUnstable=`<svg class="unstable-svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" style="width:14px;height:14px;stroke:#888"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>`;
function checkApiKeyStatus(){if(localStorage.getItem('ciri_key')){document.getElementById('status-text').textContent="Secure";document.getElementById('status-icon').innerHTML=svgSecure;}else{document.getElementById('status-text').textContent="Unstable";document.getElementById('status-icon').innerHTML=svgUnstable;}}
window.closeCiri=function(){uiBody.classList.remove('ciri-active');isCiriActive=false;if(screenStream&&MODES[currentModeIndex]!=='LIVE'){screenStream.getTracks().forEach(t=>t.stop());screenStream=null;}};
window.autoGrow=function(el){el.style.height="5px";el.style.height=(el.scrollHeight)+"px";};
window.cycleMode=async function(){currentModeIndex=(currentModeIndex+1)%MODES.length;document.getElementById('mode-toggle').textContent=MODES[currentModeIndex];document.getElementById('mode-toggle').className=MODES[currentModeIndex]==='LIVE'?'live-active':'';if(MODES[currentModeIndex]==='LIVE'){try{screenStream=await navigator.mediaDevices.getDisplayMedia({video:{displaySurface:"monitor"}});document.getElementById('screen-video').srcObject=screenStream;appendCiriMsg("ciri","LIVE Vision active. I can now see your screen.");}catch(err){appendCiriMsg("ciri","Failed to access screen. Reverting mode.");cycleMode();}}else{if(screenStream){screenStream.getTracks().forEach(t=>t.stop());screenStream=null;}}};
window.handleFileUpload=function(e){if(e.target.files&&e.target.files[0]){const r=new FileReader();r.onload=(ev)=>{currentImageBase64=ev.target.result.split(',')[1];currentImageMime=e.target.files[0].type;document.getElementById('img-preview').src=ev.target.result;document.getElementById('img-preview-box').style.display='flex';};r.readAsDataURL(e.target.files[0]);}};
window.clearImage=function(){currentImageBase64=null;currentImageMime=null;document.getElementById('img-preview-box').style.display='none';document.getElementById('file-upload').value="";};
document.getElementById('chat-input').addEventListener('keypress',(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();handleSend();}});
window.handleSend=async function(){
 const ci=document.getElementById('chat-input');const text=ci.value.trim();if(!text&&!currentImageBase64)return;
 if(expectingApiKey){localStorage.setItem('ciri_key',text);ci.value='';ci.style.height='auto';expectingApiKey=false;document.getElementById('status-text').textContent="Secure";document.getElementById('status-icon').innerHTML=svgSecure;appendCiriMsg("ciri","API Key secured.");return;}
 const apiKey=localStorage.getItem('ciri_key');if(!apiKey){appendCiriMsg("user",text);ci.value='';ci.style.height='auto';expectingApiKey=true;appendCiriMsg("ciri","Please provide your Gemini API key.");return;}
 appendCiriMsg("user",text,document.getElementById('img-preview').src);ci.value='';ci.style.height='auto';const payloadImage=currentImageBase64;const payloadMime=currentImageMime;clearImage();document.getElementById('action-orb').classList.add('thinking');
 const tempLoadingId="loading-"+Date.now();let loadingHtml=`<div class="message ciri" id="${tempLoadingId}"><span style="color: #a1a1aa; font-style: italic; font-weight: 500;">Processing...</span></div>`;document.getElementById('chat-history').insertAdjacentHTML('beforeend',loadingHtml);document.getElementById('chat-history').scrollTop=document.getElementById('chat-history').scrollHeight;
 const parts=[];if(text)parts.push({text:text});if(payloadImage)parts.push({inline_data:{mime_type:payloadMime,data:payloadImage}});
 if(MODES[currentModeIndex]==='LIVE'&&screenStream){const cvs=document.getElementById('screen-canvas');const vid=document.getElementById('screen-video');cvs.width=vid.videoWidth;cvs.height=vid.videoHeight;cvs.getContext('2d').drawImage(vid,0,0);const screenB64=cvs.toDataURL('image/jpeg',0.8).split(',')[1];if(screenB64)parts.push({inline_data:{mime_type:"image/jpeg",data:screenB64}});}
 const requestBody={contents:[{parts:parts}]};if(MODES[currentModeIndex]==='THINKING'){requestBody.system_instruction={parts:[{text:"You are Ciri, an advanced AI. You MUST think step-by-step before answering. Enclose your entirely literal, internal thought process inside <think>...</think> tags. After the closing </think> tag, provide your final formatted answer. You are also an expert mathematician. Always use standard LaTeX for math. Use $$ for block equations and $ for inline equations."}]};}else{requestBody.system_instruction={parts:[{text:"You are Ciri. You are an expert mathematician. Always use standard LaTeX for math. Use $$ for block equations and $ for inline equations."}]};}
 try{
  const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(requestBody)});
  const data=await res.json();if(data.error)throw new Error(data.error.message);
  let responseText=data.candidates[0].content.parts[0].text;let realThoughts="";if(MODES[currentModeIndex]==='THINKING'){const thinkMatch=responseText.match(/<think>([\s\S]*?)<\/think>/);if(thinkMatch){realThoughts=thinkMatch[1].trim();responseText=responseText.replace(/<think>[\s\S]*?<\/think>/,'').trim();}}
  document.getElementById(tempLoadingId).remove();document.getElementById('action-orb').classList.remove('thinking');await typeMarkdownResponse(responseText,realThoughts);
 }catch(err){document.getElementById(tempLoadingId).remove();document.getElementById('action-orb').classList.remove('thinking');await typeMarkdownResponse("Error: "+err.message);}
};
function appendCiriMsg(sender,text,imgSrc=null){const div=document.createElement('div');div.className=`message ${sender}`;let html="";if(imgSrc&&imgSrc!==window.location.href)html+=`<img src="${imgSrc}" style="max-width: 100%; border-radius: 12px; margin-bottom: 12px;">`;if(text)html+=marked.parse(text);div.innerHTML=html;document.getElementById('chat-history').appendChild(div);if(window.MathJax)MathJax.typesetPromise([div]);document.getElementById('chat-history').scrollTop=document.getElementById('chat-history').scrollHeight;}
function typeMarkdownResponse(fullText,realThoughts=""){return new Promise((resolve)=>{const div=document.createElement('div');div.className='message ciri';let htmlStructure="";if(realThoughts){htmlStructure+=`<details class="thought-process"><summary>Internal Monologue</summary><div class="thought-content">${realThoughts.replace(/</g,'&lt;').replace(/>/g,'&gt;')}</div></details>`;}const contentDiv=document.createElement('div');div.innerHTML=htmlStructure;div.appendChild(contentDiv);document.getElementById('chat-history').appendChild(div);let i=0;let currentStr="";const speed=MODES[currentModeIndex]==='FAST'?2:5;const chunkSize=MODES[currentModeIndex]==='FAST'?4:2;function typeChar(){if(i<fullText.length){currentStr+=fullText.substring(i,i+chunkSize);i+=chunkSize;contentDiv.innerHTML=marked.parse(currentStr);if(window.MathJax)MathJax.typesetPromise([contentDiv]);document.getElementById('chat-history').scrollTop=document.getElementById('chat-history').scrollHeight;setTimeout(typeChar,speed);}else{contentDiv.innerHTML=marked.parse(fullText);if(window.MathJax)MathJax.typesetPromise([contentDiv]);resolve();}}typeChar();});}

// CINE-NOTI
let activeMedia=null;let notiHideTimeout;const cineNoti=document.getElementById('cine-noti');
function showNoti(){cineNoti.classList.add('active');cineNoti.classList.remove('minimized');document.getElementById('restore-btn').classList.remove('visible');resetNotiHideTimer();}
function hideNoti(){cineNoti.classList.remove('active');cineNoti.classList.remove('minimized');document.getElementById('restore-btn').classList.remove('visible');clearTimeout(notiHideTimeout);}
function resetNotiHideTimer(){clearTimeout(notiHideTimeout);if(cineNoti.classList.contains('active')&&!cineNoti.classList.contains('minimized')){notiHideTimeout=setTimeout(()=>{cineNoti.classList.add('minimized');setTimeout(()=>document.getElementById('restore-btn').classList.add('visible'),300);},5000);}}
cineNoti.addEventListener('mouseenter',()=>clearTimeout(notiHideTimeout));cineNoti.addEventListener('mouseleave',resetNotiHideTimer);
document.getElementById('minimize-noti-btn').onclick=()=>{cineNoti.classList.add('minimized');setTimeout(()=>document.getElementById('restore-btn').classList.add('visible'),300);};
document.getElementById('restore-btn').onclick=()=>{document.getElementById('restore-btn').classList.remove('visible');cineNoti.classList.remove('minimized');resetNotiHideTimer();};
document.getElementById('close-noti-btn').onclick=()=>{if(activeMedia)activeMedia.pause();hideNoti();};

setInterval(()=>{
 let found=null;
 document.querySelectorAll('audio, video').forEach(m=>{if(!m.paused&&!m.muted&&m.volume>0&&!['bg-video','lock-video','boot-video'].includes(m.id))found=m;});
 document.querySelectorAll('iframe').forEach(ifr=>{try{let idoc=ifr.contentDocument||ifr.contentWindow.document;if(idoc){idoc.querySelectorAll('audio, video').forEach(m=>{if(!m.paused&&!m.muted&&m.volume>0)found=m;});}}catch(e){}});
 isMediaPlaying=!!found;
 if(found!==activeMedia){if(found){activeMedia=found;setupMediaListeners();showNoti();}else{activeMedia=null;hideNoti();}}
 if(activeMedia){
  document.getElementById('current-time').textContent=formatTime(activeMedia.currentTime);
  if(isFinite(activeMedia.duration)&&activeMedia.duration>0){
   document.getElementById('progress-fill').style.width=`${(activeMedia.currentTime/activeMedia.duration)*100}%`;
   document.getElementById('total-time').textContent=formatTime(activeMedia.duration);
  }
 }
},1000);

function setupMediaListeners(){
 if(!activeMedia)return;document.getElementById('noti-title').innerText=activeMedia.title||"Web Media Playing";
 document.getElementById('play-pause').onclick=()=>{activeMedia.paused?activeMedia.play():activeMedia.pause();resetNotiHideTimer();};
 activeMedia.addEventListener('play',()=>{document.getElementById('icon-play').style.display='none';document.getElementById('icon-pause').style.display='block';showNoti();});
 activeMedia.addEventListener('pause',()=>{document.getElementById('icon-play').style.display='block';document.getElementById('icon-pause').style.display='none';});
 document.getElementById('skip-back').onclick=()=>{if(isFinite(activeMedia.currentTime))activeMedia.currentTime=Math.max(0,activeMedia.currentTime-15);resetNotiHideTimer();};
 document.getElementById('skip-forward').onclick=()=>{if(isFinite(activeMedia.duration)&&activeMedia.duration>0)activeMedia.currentTime=Math.min(activeMedia.duration,activeMedia.currentTime+15);resetNotiHideTimer();};
 document.getElementById('progress-hit-area').onclick=(e)=>{if(isFinite(activeMedia.duration)&&activeMedia.duration>0){const rect=document.getElementById('progress-hit-area').getBoundingClientRect();const percent=(e.clientX-rect.left)/rect.width;activeMedia.currentTime=percent*activeMedia.duration;}resetNotiHideTimer();};
}
function formatTime(s){if(isNaN(s)||!isFinite(s))return"0:00";const m=Math.floor(s/60);const se=Math.floor(s%60);return `${m}:${se.toString().padStart(2,'0')}`;}
function drawFakeVisualizer(){requestAnimationFrame(drawFakeVisualizer);const cvs=document.getElementById('visualizer');const ctx=cvs.getContext('2d');cvs.width=cvs.parentElement.clientWidth;cvs.height=14;const bufferLength=32;ctx.clearRect(0,0,cvs.width,cvs.height);const barW=(cvs.width/bufferLength)*2;let x=0;for(let i=0;i<bufferLength;i++){const barH=activeMedia&&!activeMedia.paused?(Math.random()*cvs.height):2;ctx.fillStyle=`#fff`;ctx.beginPath();ctx.roundRect(x,cvs.height-barH,barW-1.5,barH,2);ctx.fill();x+=barW;}}drawFakeVisualizer();
